Repository apolloconfig/apollo, pull requests merged in 2019-11, with the labels that each got.

#2726 Update config.html
  apollo-portal/src/main/resources/static/config.html
Labels: enhancement, ui

#2746 Fix maven build WARNING
  apollo-portal/pom.xml
Labels: enhancement

#2733 修改添加ApolloPropertySources到env中的逻辑，添加列表判断操作
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/config/PropertySourcesProcessor.java
Labels: client, enhancement

#2771 clean code.
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java
Labels: client

#2784 fix #2768
  apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js
Labels: bug, ui

#2805 解决 AppId 为 search 时和搜索接口 apps/search 产生的冲突
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AppController.java
  apollo-portal/src/main/resources/static/scripts/directive/directive.js
Labels: backend, bug
