Repository apolloconfig/apollo, pull requests merged in 2019-10, with the labels that each got.

#2581 Add OpenAPI to rollback config. (#2351)
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ReleaseController.java
Labels: backend, enhancement, openApi

#2630 java client's long polling timeout is 90 seconds, so server side long polling timeout must be less than 90
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
Labels: enhancement

#2642 health check can be simpler
  apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/AdminServiceHealthIndicator.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/ConfigServiceHealthIndicator.java
Labels: backend, enhancement

#2646 fix setting null value of property in xml throws NullPointerException
  apollo-client/src/main/java/com/ctrip/framework/apollo/spring/property/PlaceholderHelper.java
Labels: backend, bug

#2645 fix delete children clusters twice.
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/AdminService.java
Labels: backend, bug

#2678 Bugfix: fix miscellaneous bugs and polish code
  apollo-client/src/main/java/com/ctrip/framework/apollo/util/ConfigUtil.java
  apollo-mockserver/src/main/java/com/ctrip/framework/apollo/mockserver/EmbeddedApollo.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/LdapProperties.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripMQService.java
Labels: bug, enhancement

#2648 fix #2092.
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/wrapper/DeferredResultWrapper.java
Labels: ConfigService, backend, bug

#2684 Revert "fix #2092."
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/wrapper/DeferredResultWrapper.java
Labels: TBD

#2680 support dataChangeLastModifiedBy display after edited in a namespace
  apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/utils/ConfigChangeContentBuilder.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/MockBeanFactory.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/utils/ConfigChangeContentBuilderTest.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/api/AdminServiceAPI.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/bo/ItemBO.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/NamespaceService.java
Labels: backend, enhancement

#2705 Feature: sort table
  apollo-portal/src/main/resources/static/views/component/namespace-panel-branch-tab.html
  apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html
Labels: backend, enhancement, ui

#2696 fix #2092.
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/wrapper/DeferredResultWrapper.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/controller/NotificationControllerV2Test.java
Labels: backend, enhancement
