Repository apolloconfig/apollo, pull requests merged in 2019-12, with the labels that each got.

#2754 针对portal添加基于path的反向代理支持
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/PrefixPathController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java
  apollo-portal/src/main/resources/static/app/setting.html
  apollo-portal/src/main/resources/static/cluster.html
  apollo-portal/src/main/resources/static/config.html
  apollo-portal/src/main/resources/static/config/history.html
  apollo-portal/src/main/resources/static/delete_app_cluster_namespace.html
  apollo-portal/src/main/resources/static/login.html
  apollo-portal/src/main/resources/static/namespace/role.html
  apollo-portal/src/main/resources/static/scripts/AppUtils.js
  apollo-portal/src/main/resources/static/scripts/app.js
  apollo-portal/src/main/resources/static/scripts/controller/AppController.js
  apollo-portal/src/main/resources/static/scripts/controller/IndexController.js
  apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/ConfigBaseInfoController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/ConfigNamespaceController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/DiffConfigController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/SyncConfigController.js
  apollo-portal/src/main/resources/static/scripts/directive/delete-namespace-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/diff-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/directive.js
  apollo-portal/src/main/resources/static/scripts/directive/gray-release-rules-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/item-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/merge-and-publish-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/publish-deny-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/release-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/rollback-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/show-text-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/services/AppService.js
  apollo-portal/src/main/resources/static/scripts/services/CommitService.js
  apollo-portal/src/main/resources/static/scripts/services/CommonService.js
  apollo-portal/src/main/resources/static/scripts/services/ConfigService.js
  apollo-portal/src/main/resources/static/scripts/services/ConsumerService.js
  apollo-portal/src/main/resources/static/scripts/services/EnvService.js
  apollo-portal/src/main/resources/static/scripts/services/FavoriteService.js
  apollo-portal/src/main/resources/static/scripts/services/InstanceService.js
  apollo-portal/src/main/resources/static/scripts/services/NamespaceBranchService.js
  apollo-portal/src/main/resources/static/scripts/services/NamespaceService.js
  apollo-portal/src/main/resources/static/scripts/services/OrganizationService.js
  apollo-portal/src/main/resources/static/scripts/services/PermissionService.js
  apollo-portal/src/main/resources/static/scripts/services/ReleaseHistoryService.js
  apollo-portal/src/main/resources/static/scripts/services/ReleaseService.js
  apollo-portal/src/main/resources/static/scripts/services/ServerConfigService.js
  apollo-portal/src/main/resources/static/scripts/services/SystemInfoService.js
  apollo-portal/src/main/resources/static/scripts/services/SystemRoleService.js
  apollo-portal/src/main/resources/static/scripts/services/UserService.js
  apollo-portal/src/main/resources/static/system-role-manage.html
  apollo-portal/src/main/resources/static/system_info.html
  apollo-portal/src/main/resources/static/views/common/footer.html
  apollo-portal/src/main/resources/static/views/common/nav.html
  apollo-portal/src/main/resources/static/views/component/namespace-panel-branch-tab.html
  apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html
  apollo-portal/src/main/resources/static/views/component/rollback-modal.html
Labels: enhancement, ui

#2814 fix NPE when ReleaseComment is null.
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/emailbuilder/ConfigPublishEmailBuilder.java
Labels: bug

#2849 Fixed an issue with openapi item comment being too long。#2823
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java
Labels: bug, openApi
