Repository apolloconfig/apollo, pull requests merged in 2021-06, with the labels that each got.

#3747 add CHANGES.md for track.
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES.md
Labels: area/operations

#3666 feat(apollo-client): add method interestedChangedKeys to ConfigChangeEvent
  CHANGES.md
  apollo-client/src/main/java/com/ctrip/framework/apollo/internals/AbstractConfig.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/internals/DefaultConfig.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/internals/InterestedConfigChangeEvent.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/internals/SimpleConfig.java
  apollo-client/src/main/java/com/ctrip/framework/apollo/model/ConfigChangeEvent.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/internals/AbstractConfigTest.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/internals/DefaultConfigTest.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/internals/InterestedConfigChangeEventTest.java
  apollo-client/src/test/java/com/ctrip/framework/apollo/spring/JavaConfigAnnotationTest.java
Labels: enhancement

#3753 Fix typo on "load from specified cluster fist"
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/service/config/AbstractConfigService.java
Labels: chore

#3758 Fix typo on doc "development guide" chapter 2.3.3
  docs/zh/development/apollo-development-guide.md
Labels: area/document

#3647 feat(open-api): get authorized apps
  CHANGES.md
  apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/ApolloOpenApiClient.java
  apollo-openapi/src/main/java/com/ctrip/framework/apollo/openapi/client/service/AppOpenApiService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/service/ConsumerService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/AppController.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/openapi/service/ConsumerServiceIntegrationTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/openapi/v1/controller/AppControllerIntegrationTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/openapi/v1/controller/AppControllerTest.java
  apollo-portal/src/test/resources/sql/cleanup.sql
  apollo-portal/src/test/resources/sql/openapi/ConsumerServiceIntegrationTest.testFindAppIdsAuthorizedByConsumerId.sql
Labels: area/openapi, feature
