Repository apolloconfig/apollo, pull requests merged in 2021-08, with the labels that each got.

#3836 feature: public namespace support different formats
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AppNamespaceService.java
  apollo-portal/src/main/resources/static/namespace.html
  apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js
  apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
  apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html
Labels: summer-2021

#3871 Summer2021 support more format
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AppNamespaceService.java
  apollo-portal/src/main/resources/static/namespace.html
  apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/service/AppNamespaceServiceTest.java
Labels: summer-2021

#3894 fix search history.
  CHANGES.md
  apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
Labels: bug, area/ui

#3920 remove ctrip profile
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/config/PortalConfig.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/EmailConfiguration.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/MQConfiguration.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/BizLoggingCustomizer.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripEmailRequestBuilder.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripEmailService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripLogoutHandler.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripMQService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripSsoHeartbeatHandler.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripUserInfoHolder.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripUserService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/WebContextConfiguration.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/ctrip/filters/UserAccessFilter.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/package-info.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/spi/ctrip/CtripUserServiceTest.java
  pom.xml
Labels: area/portal

#3927 Fix broken starchart url, and update README.md urls
  README.md
Labels: area/document
