Repository apolloconfig/apollo, pull requests merged in 2022-01, with the labels that each got.

#4193 Add unit tests for Utils
  CHANGES.md
  apollo-core/src/test/java/com/ctrip/framework/foundation/internals/UtilsTest.java
Labels: area/test

#4198 The release history of namespaces that are not properties will also show comments and release times
  CHANGES.md
  apollo-portal/src/main/resources/static/config/history.html
Labels: area/ui

#4205 build: add github-actions to CLAssistant's allowlist
  .github/workflows/cla.yml
Labels: chore
