Repository apolloconfig/apollo, pull requests merged in 2023-12, with the labels that each got.

#5030 Fix method reflection bug
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/aop/ApolloAuditSpanAspect.java
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/util/ApolloAuditUtil.java
  apollo-audit/apollo-audit-impl/src/test/java/com/ctrip/framework/apollo/audit/aop/ApolloAuditSpanAspectTest.java
  apollo-audit/apollo-audit-spring-boot-starter/pom.xml
Labels: size:M, lgtm

#5034 rename the init.h2.sql to avoid loading wrong files in quick start mode
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/BizDBPropertySource.java
  apollo-configservice/src/main/resources/jpa/configdb.init.h2.sql
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/PortalDBPropertySource.java
  apollo-portal/src/main/resources/jpa/portaldb.init.h2.sql
Labels: size:XS, lgtm

#5036 upgrade apollo-java version to 2.2.0
  pom.xml
Labels: size:XS

#5037 some misc fix
  apollo-adminservice/src/main/resources/apollo-adminservice.conf
  apollo-configservice/src/main/resources/apollo-configservice.conf
  apollo-portal/src/assembly/assembly-descriptor.xml
  apollo-portal/src/main/resources/apollo-portal.conf
Labels: size:S

#5038 bump version to 2.2.0
  pom.xml
Labels: size:XS

#5049 bump version to 2.3.0-SNAPSHOT
  CHANGES.md
  changes/changes-2.2.0.md
  pom.xml
Labels: size:M

#5050 adjust the sql a little bit so that ddl is before dml
  scripts/sql/apolloconfigdb.sql
  scripts/sql/apolloportaldb.sql
Labels: size:L

#5055 Fix circular references on LdapAutoConfiguration
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration.java
Labels: size:XS, lgtm

#5046 docs: openapi 3.2.17 Create App And grant administrative privileges
  docs/en/usage/apollo-open-api-platform.md
  docs/zh/usage/apollo-open-api-platform.md
Labels: size:M, lgtm
