Repository apolloconfig/apollo, pull requests merged in 2024-12, with the labels that each got.

#5287 feat: add JSON format button in apollo-portal
  CHANGES.md
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/img/brush.png
  apollo-portal/src/main/resources/static/scripts/directive/item-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
  apollo-portal/src/main/resources/static/views/component/item-modal.html
  apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html
Labels: size:M, lgtm

#5291 add missing url patterns for AdminServiceAuthenticationFilter
  CHANGES.md
  apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/AdminServiceAutoConfiguration.java
Labels: size:XS

#5297 upgrade cache action version
  .github/workflows/build.yml
Labels: size:XS

#5298 support java.time.Instant serialization with gson
  CHANGES.md
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/controller/HttpMessageConverterConfiguration.java
Labels: size:S

#5293 Code style-Optimize some code structures to improve readability
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/component/ApolloAuditLogApiJpaImpl.java
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/component/ApolloAuditLogApiNoOpImpl.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Audit.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Cluster.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Item.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Namespace.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Privilege.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Release.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/ReleaseHistory.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/ServerConfig.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/registry/DatabaseServiceRegistryImpl.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/registry/configuration/support/ApolloServiceRegistryProperties.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/utils/ReleaseMessageKeyGenerator.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/utils/ReleaseKeyGeneratorTest.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/datasource/ApolloDataSourceScriptDatabaseInitializerFactory.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/App.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/AppNamespace.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/BaseEntity.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/PortalSettings.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/RestTemplateFactory.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/SystemInfoController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/ServerConfig.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRoleInitializationService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultUserService.java
Labels: size:M, lgtm

#5295 Add usage instructions for multiple appid in the Apollo client
  docs/en/client/java-sdk-user-guide.md
  docs/zh/client/java-sdk-user-guide.md
Labels: size:M, lgtm
