Repository apolloconfig/apollo, pull requests merged in 2024-01, with the labels that each got.

#5072 Add comment for clusters and UI display
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Cluster.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/dto/ClusterDTO.java
  apollo-portal/src/main/resources/static/cluster.html
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/scripts/controller/ClusterController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/ConfigBaseInfoController.js
  scripts/sql/apolloconfigdb.sql
  scripts/sql/delta/v220-v230/apolloconfigdb-v220-v230.sql
Labels: size:M, lgtm

#5078 Fix the issue that the length of private namespaces are mis-calculated
  CHANGES.md
  apollo-portal/src/main/resources/static/scripts/controller/NamespaceController.js
Labels: size:XS

#5082 Refine the description of the environment name
  docs/en/deployment/distributed-deployment-guide.md
  docs/en/faq/common-issues-in-deployment-and-development-phase.md
  docs/zh/deployment/distributed-deployment-guide.md
  docs/zh/faq/common-issues-in-deployment-and-development-phase.md
Labels: size:XS, lgtm
