Repository apolloconfig/apollo, pull requests merged in 2024-10, with the labels that each got.

#5232 solve the problem of duplicate comments and blank lines
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/txtresolver/PropertyResolver.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ItemService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/NamespaceService.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/component/txtresolver/PropertyResolverTest.java
Labels: size:L, lgtm

#5228 feat: add determine appid+cluster namespace num limit logic
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/repository/NamespaceRepository.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/NamespaceService.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/service/NamespaceServiceIntegrationTest.java
  doc/images/namespace-num-limit-enabled.png
  doc/images/namespace-num-limit-white.png
  doc/images/namespace-num-limit.png
  docs/en/portal/apollo-user-guide.md
  docs/zh/portal/apollo-user-guide.md
Labels: size:L, lgtm

#5236 feat: add observe status access-key for pre-check and logging only (#5216)
  CHANGES.md
  apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/AccessKeyController.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/AccessKey.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/AccessKeyService.java
  apollo-biz/src/test/resources/sql/accesskey-test.sql
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/constants/AccessKeyMode.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/dto/AccessKeyDTO.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/filter/ClientAuthenticationFilter.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/service/AccessKeyServiceWithCache.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/AccessKeyUtil.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/filter/ClientAuthenticationFilterTest.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/api/AdminServiceAPI.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AccessKeyController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AccessKeyService.java
  apollo-portal/src/main/resources/static/app/access_key.html
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/scripts/controller/AccessKeyController.js
  apollo-portal/src/main/resources/static/scripts/services/AccessKeyService.js
  changes/changes-2.4.0.md
  scripts/sql/profiles/h2-default/apolloconfigdb.sql
  scripts/sql/profiles/h2-default/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/profiles/mysql-database-not-specified/apolloconfigdb.sql
  scripts/sql/profiles/mysql-database-not-specified/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/profiles/mysql-default/apolloconfigdb.sql
  scripts/sql/profiles/mysql-default/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/src/apolloconfigdb.sql
  scripts/sql/src/delta/v230-v240/apolloconfigdb-v230-v240.sql
Labels: size:L, lgtm

#5227 feat: add determine single namespace item num limit logic
  CHANGES.md
  apollo-adminservice/src/main/java/com/ctrip/framework/apollo/adminservice/controller/ItemController.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/repository/ItemRepository.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/ItemService.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/ItemSetService.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/service/ItemSetServiceTest.java
  apollo-biz/src/test/resources/sql/itemset-test.sql
  doc/images/item-num-limit-enabled.png
  doc/images/item-num-limit.png
  docs/en/portal/apollo-user-guide.md
  docs/zh/portal/apollo-user-guide.md
Labels: size:L, lgtm

#5247 feat: ConfigService cache record stats
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/ConfigServiceAutoConfiguration.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/service/config/ConfigServiceWithCache.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/service/config/ConfigServiceWithCacheAndCacheKeyIgnoreCaseTest.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/service/config/ConfigServiceWithCacheTest.java
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:L, lgtm

#5248 fix：RefreshAdminServerAddressTask supports dynamic configuration of time interval
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/AdminServiceAddressLocator.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/config/PortalConfig.java
Labels: size:M, lgtm

#5251 fix：Optimize the default log path configuration
  apollo-assembly/src/main/resources/application.yml
  apollo-configservice/src/main/resources/configservice.properties
  docs/en/contribution/apollo-development-guide.md
  docs/zh/contribution/apollo-development-guide.md
Labels: size:XS, lgtm

#5262 refactor: Configuration files uniformly use Kebab style
  CHANGES.md
  apollo-adminservice/src/main/resources/application-database-discovery.properties
  apollo-adminservice/src/main/resources/application.yml
  apollo-adminservice/src/test/resources/application.yml
  apollo-assembly/src/main/resources/application-database-discovery.properties
  apollo-assembly/src/main/resources/application.yml
  apollo-configservice/src/main/resources/application-database-discovery.properties
  apollo-configservice/src/main/resources/application.yml
  apollo-configservice/src/test/resources/application.yml
  apollo-portal/src/main/resources/application-ldap-activedirectory-sample.yml
  apollo-portal/src/main/resources/application-ldap-apacheds-sample.yml
  apollo-portal/src/main/resources/application-ldap-openldap-sample.yml
  docs/en/client/java-sdk-user-guide.md
  docs/en/deployment/distributed-deployment-guide.md
  docs/en/extension/portal-how-to-implement-user-login-function.md
  docs/zh/client/java-sdk-user-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
  docs/zh/extension/portal-how-to-implement-user-login-function.md
Labels: size:L, lgtm

#5233 [Docs]OSPP Support Kubernetes ConfigMap for Apollo java, golang client
  docs/en/client/java-sdk-user-guide.md
  docs/zh/client/java-sdk-user-guide.md
Labels: size:L, lgtm
