Repository apolloconfig/apollo, pull requests merged in 2024-11, with the labels that each got.

#5249 feat: openapi query namespace support not fill item
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/server/service/ServerNamespaceOpenApiService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/NamespaceController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ConfigsExportService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/NamespaceService.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/service/ConfigsExportServiceTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/service/NamespaceServiceTest.java
  pom.xml
Labels: size:L, lgtm

#5263 refactor(sql): align database ClusterName and NamespaceName fields lengths
  CHANGES.md
  scripts/sql/profiles/h2-default/apolloconfigdb.sql
  scripts/sql/profiles/h2-default/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/profiles/mysql-database-not-specified/apolloconfigdb.sql
  scripts/sql/profiles/mysql-database-not-specified/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/profiles/mysql-default/apolloconfigdb.sql
  scripts/sql/profiles/mysql-default/delta/v230-v240/apolloconfigdb-v230-v240.sql
  scripts/sql/src/apolloconfigdb.sql
  scripts/sql/src/delta/v230-v240/apolloconfigdb-v230-v240.sql
Labels: size:L, lgtm

#5264 feat(biz): Added the value length limit function for AppId-level configuration items
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/service/ItemService.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/config/BizConfigTest.java
  apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/service/ItemServiceTest.java
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:L, lgtm

#5272 chore: typo fix
  apollo-common/pom.xml
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/PortalOpenApiConfig.java
  docs/en/client/other-language-client-user-guide.md
  docs/zh/client/other-language-client-user-guide.md
  scripts/openapi/bash/openapi-usage-example.sh
  scripts/openapi/bash/openapi.sh
Labels: size:S, lgtm

#5277 fix: keep clusters order in envclusters openapi
  CHANGES.md
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/BeanUtils.java
Labels: size:XS, lgtm

#5280 Bump com.thoughtworks.xstream:xstream from 1.4.20 to 1.4.21 to fix CVE-2024-47072
  CHANGES.md
  pom.xml
Labels: size:XS, lgtm

#5274 Create quick-start-btpanel.md
  docs/en/_sidebar.md
  docs/en/deployment/third-party-tool-btpanel.md
  docs/en/images/deployment/btpanel/addApollo.png
  docs/en/images/deployment/btpanel/console.png
  docs/en/images/deployment/btpanel/install-Apollo.png
  docs/en/images/deployment/btpanel/install.png
  docs/en/images/deployment/btpanel/install2.png
  docs/zh/_sidebar.md
  docs/zh/deployment/third-party-tool-btpanel.md
  docs/zh/images/deployment/btpanel/console.png
  docs/zh/images/deployment/btpanel/docker-menu.png
  docs/zh/images/deployment/btpanel/install-docker.png
  docs/zh/images/deployment/btpanel/search-apollo.png
Labels: size:L, lgtm

#5282 feat: highlight diffs for properties
  CHANGES.md
  apollo-portal/src/main/resources/static/config/diff.html
  apollo-portal/src/main/resources/static/config/history.html
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/scripts/controller/config/DiffConfigController.js
  apollo-portal/src/main/resources/static/scripts/controller/config/ReleaseHistoryController.js
  apollo-portal/src/main/resources/static/scripts/directive/diff-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/release-modal-directive.js
  apollo-portal/src/main/resources/static/scripts/directive/show-text-modal-directive.js
  apollo-portal/src/main/resources/static/styles/common-style.css
  apollo-portal/src/main/resources/static/views/component/diff.html
  apollo-portal/src/main/resources/static/views/component/release-modal.html
  apollo-portal/src/main/resources/static/views/component/show-text-modal.html
Labels: size:L, lgtm
