Repository apolloconfig/apollo, pull requests merged in 2024-08, with the labels that each got.

#5191 fix: assign roles to owner instead of operator
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRoleInitializationService.java
Labels: size:XS, lgtm

#5192 add namespaces check in synchronization configuration feature
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ItemController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/model/NamespaceSyncModel.java
Labels: size:S

#5194 bump version to 2.3.0
  pom.xml
Labels: size:XS

#5202 bump version to 2.4.0-SNAPSHOT
  CHANGES.md
  changes/changes-2.3.0.md
  pom.xml
Labels: size:M

#5204 update the server config link system info page
  CHANGES.md
  apollo-portal/src/main/resources/static/system_info.html
Labels: size:XS, lgtm

#5200 feat: support portal restTemplate Client connection pool config
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/RestTemplateFactory.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/config/PortalConfig.java
Labels: size:S, lgtm

#5220 chore: beautify footer: github -> GitHub
  apollo-portal/src/main/resources/static/views/common/footer.html
Labels: size:XS, lgtm
