Repository apolloconfig/apollo, pull requests merged in 2024-04, with the labels that each got.

#5121 feat: Portal 模块 RestTemplate 支持配置 ConnectionTimeToLive
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/RestTemplateFactory.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/config/PortalConfig.java
Labels: size:XS, lgtm

#5131 feat: update the config item table column width
  CHANGES.md
  apollo-portal/src/main/resources/static/views/component/namespace-panel-branch-tab.html
  apollo-portal/src/main/resources/static/views/component/namespace-panel-master-tab.html
Labels: size:M, lgtm

#5134 sync apollo portal server config to apollo quick start server
  CHANGES.md
  apollo-assembly/src/main/resources/application.yml
Labels: size:S
