Repository apolloconfig/apollo, pull requests merged in 2024-03, with the labels that each got.

#5105 fix the apollo version logic by reading the server version instead of the apollo-core version
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/constants/ApolloServer.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/controller/ApolloInfoController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/SystemInfoController.java
Labels: size:M

#5112 build: bump org.postgresal:postgresal from 42.5.3 to 42.7.2
  pom.xml
Labels: size:XS, lgtm

#5111 ci: add convertional commit lint
  .github/workflows/build.yml
  .github/workflows/commit_lint.yml
  .github/workflows/license.yml
  CONTRIBUTING.md
Labels: size:S, lgtm

#5116 update the quick start doc to reflect the latest changes
  docs/en/deployment/quick-start.md
  docs/zh/deployment/quick-start.md
Labels: size:L
