Repository apolloconfig/apollo, pull requests merged in 2024-06, with the labels that each got.

#5150 Fix the role permission deletion issue when appid contains '_'
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/repository/PermissionRepository.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/repository/RoleRepository.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java
Labels: size:S

#5153 Fix npe of audit log get operator
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/context/ApolloAuditTracer.java
  apollo-audit/apollo-audit-impl/src/main/java/com/ctrip/framework/apollo/audit/spi/defaultimpl/ApolloAuditOperatorDefaultSupplier.java
  apollo-audit/apollo-audit-impl/src/test/java/com/ctrip/framework/apollo/audit/spi/ApolloAuditOperatorSupplierTest.java
Labels: size:M, lgtm

#5157 fix: -XX:HeapDumpPath doesn't ready when meet OOM
  CHANGES.md
  apollo-adminservice/src/main/scripts/startup.sh
  apollo-configservice/src/main/scripts/startup.sh
  apollo-portal/src/main/scripts/startup.sh
Labels: area/configservice, area/portal, area/adminservice, size:XS, lgtm

#5162 Fix the release retention error
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/AccessKey.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Audit.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Cluster.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Commit.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/GrayReleaseRule.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Item.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Namespace.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Privilege.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/Release.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/ReleaseHistory.java
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/entity/ServerConfig.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/App.java
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/entity/AppNamespace.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/entity/Consumer.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/entity/ConsumerRole.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/entity/ConsumerToken.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/Favorite.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/Permission.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/Role.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/RolePermission.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/ServerConfig.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/po/UserRole.java
Labels: size:M, lgtm
