Repository apolloconfig/apollo, pull requests merged in 2025-01, with the labels that each got.

#5305 typo: portal access admin service
  docs/en/design/apollo-design.md
  docs/zh/design/apollo-design.md
Labels: size:XS, lgtm

#5229 [Docs]OSPP-Add more observability in apollo config client
  doc/images/apollo-client-monitor-jmx.jpg
  doc/images/apollo-client-monitor-prometheus.png
  docs/en/client/java-sdk-user-guide.md
  docs/zh/client/java-sdk-user-guide.md
Labels: size:XL, lgtm

#5310 docs(charts): 更新 Helm chart 包和索引
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:XS, lgtm

#5302 Feat(Auth): Authorization by Env Cluster
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/PermissionValidator.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/constant/PermissionType.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/constant/RoleType.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/CommitController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsImportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ItemController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/NamespaceBranchController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/NamespaceController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/PermissionController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ReleaseController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ReleaseHistoryController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/entity/vo/ClusterNamespaceRolesAssignedUsers.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AppService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ClusterService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/RoleInitializationService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRoleInitializationService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/util/RoleUtils.java
  apollo-portal/src/main/resources/static/app/manage_cluster.html
  apollo-portal/src/main/resources/static/cluster/ns_role.html
  apollo-portal/src/main/resources/static/config.html
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/scripts/app.js
  apollo-portal/src/main/resources/static/scripts/controller/ManageClusterController.js
  apollo-portal/src/main/resources/static/scripts/controller/role/ClusterNamespaceRoleController.js
  apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
  apollo-portal/src/main/resources/static/scripts/services/PermissionService.js
  apollo-portal/src/main/resources/static/styles/common-style.css
  apollo-portal/src/test/java/com/ctrip/framework/apollo/ControllableAuthorizationConfiguration.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/SkipAuthorizationConfiguration.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/controller/ItemControllerAuthIntegrationTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/controller/PermissionControllerTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/service/AppServiceTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/spi/defaultImpl/RoleInitializationServiceTest.java
  doc/images/manage_cluster_entry.png
  doc/images/ns-permission-app-allns-entry.png
  doc/images/ns-permission-app-allns-select.png
  doc/images/ns-permission-app-env-cluster-edit.png
  doc/images/ns-permission-app-env-cluster-entry.png
  doc/images/ns-permission-app-env-ns-select.png
  docs/en/portal/apollo-user-guide.md
  docs/zh/portal/apollo-user-guide.md
Labels: size:XXL, lgtm

#5316 optimize: pre check dataChangeCreatedBy in updateItem
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java
Labels: size:XS, lgtm

#5317 fix apollo-on-kubernetes link
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:XS
