Repository apolloconfig/apollo, pull requests merged in 2025-03, with the labels that each got.

#5355 docs: add note for confiservice and adminservice
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:S, lgtm

#5356 chore: fix not-correct lint
  docs/en/portal/apollo-open-api-platform.md
  docs/zh/portal/apollo-open-api-platform.md
Labels: size:XS, lgtm

#5361 feat(configservice): Enhanced instance configuration auditing and caching
  CHANGES.md
  apollo-biz/src/main/java/com/ctrip/framework/apollo/biz/config/BizConfig.java
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtil.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/util/InstanceConfigAuditUtilTest.java
  docs/en/deployment/distributed-deployment-guide.md
  docs/zh/deployment/distributed-deployment-guide.md
Labels: size:L

#5365 feat: Provide a new open APl to return the organization list(#5349)
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/server/service/ServerOrganizationOpenApiService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/util/OpenApiBeanUtils.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/OrganizationController.java
  pom.xml
Labels: size:L, lgtm
