Repository apolloconfig/apollo, pull requests merged in 2025-02, with the labels that each got.

#5322 feat: 新增K8S集群中服务接入方式
  docs/en/_sidebar.md
  docs/en/client/k8s-configmap-user-guide.md
  docs/zh/_sidebar.md
  docs/zh/client/k8s-configmap-user-guide.md
Labels: size:S, lgtm

#5336 Provide a new configfiles API to return the raw content of configuration files directly
  CHANGES.md
  apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/ConfigFileController.java
  apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/controller/ConfigFileControllerTest.java
  docs/en/client/other-language-client-user-guide.md
  docs/zh/client/other-language-client-user-guide.md
Labels: size:L, lgtm

#5337 Refactor: align permission validator api
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/auth/ConsumerPermissionValidator.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/util/ConsumerAuthUtil.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/AppController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ClusterController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/NamespaceBranchController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/NamespaceController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ReleaseController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/audit/ApolloAuditLogQueryApiPortalPreAuthorizer.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/PermissionValidator.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/component/UserPermissionValidator.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AccessKeyController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/AppController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ClusterController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/CommitController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsExportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConfigsImportController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ConsumerController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/GlobalSearchController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ItemController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/NamespaceBranchController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/NamespaceController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/PermissionController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ReleaseController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ReleaseHistoryController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ServerConfigController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/SystemInfoController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/UserInfoController.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ConfigsExportService.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/SkipAuthorizationConfiguration.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/openapi/v1/controller/AppControllerTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/openapi/v1/controller/NamespaceControllerTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/controller/ItemControllerTest.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/service/ConfigsExportServiceTest.java
Labels: size:XL, lgtm
