Repository apolloconfig/apollo, pull requests merged in 2025-06, with the labels that each got.

#5395 bugfix: auto delete roles relate to cluster
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/repository/PermissionRepository.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/repository/RoleRepository.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/ClusterService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/RolePermissionService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultRolePermissionService.java
  apollo-portal/src/test/java/com/ctrip/framework/apollo/portal/spi/defaultImpl/RolePermissionServiceTest.java
  apollo-portal/src/test/resources/sql/permission/RolePermissionServiceTest.deleteRolePermissionsByAppIdWithClusterRoles.sql
Labels: size:L, lgtm

#5406 fix: Bump h2database and snakeyaml version
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/controller/ItemController.java
  pom.xml
Labels: size:S, lgtm

#5407 fix: correct permission target format to appId+env+namespace/cluster
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/service/AppService.java
Labels: size:XS, lgtm

#5409 add hezhangjian as pmc member
  docs/en/community/team.md
  docs/zh/community/team.md
Labels: size:M

#5414 * Hide password when registering or modifying users
  CHANGES.md
  apollo-portal/src/main/resources/static/i18n/en.json
  apollo-portal/src/main/resources/static/i18n/zh-CN.json
  apollo-portal/src/main/resources/static/scripts/controller/UserController.js
  apollo-portal/src/main/resources/static/user-manage.html
Labels: size:M, lgtm

#5415 Added links to apollo-rust-client, a new Rust based client that supports both Rust and NodeJS via WASM
  docs/en/client/nodejs-sdks-user-guide.md
  docs/en/client/rust-sdks-user-guide.md
  docs/zh/client/nodejs-sdks-user-guide.md
  docs/zh/client/rust-sdks-user-guide.md
Labels: size:S
