Repository apolloconfig/apollo, pull requests merged in 2025-04, with the labels that each got.

#5367 refactor(apollo-common): 异常处理增加根本原因信息
  CHANGES.md
  apollo-common/src/main/java/com/ctrip/framework/apollo/common/controller/GlobalDefaultExceptionHandler.java
Labels: size:S, lgtm

#5376 feat(ItemController): Enhanced parameter verification for edit item
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/ItemController.java
Labels: size:XS, lgtm

#5381 [issue-87][apollo-java]: Added a new feature to get instance count by namespace.
  CHANGES.md
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/server/service/ServerInstanceOpenApiService.java
  apollo-portal/src/main/java/com/ctrip/framework/apollo/openapi/v1/controller/InstanceController.java
Labels: size:M, lgtm
